services:
  app:
    container_name: marloy-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: db
      DATABASE_USER: marloy
      DATABASE_PASSWORD: marloy
      DATABASE_NAME: marloy
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: marloy-db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: marloy
      MYSQL_DATABASE: marloy
      MYSQL_USER: marloy
      MYSQL_PASSWORD: marloy
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env

volumes:
  db_data: